export const USER_AVATAR = "https://images6.alphacoders.com/714/714397.jpg";

export const OPTIONS = {
  method: "GET",
  headers: {
    accept: "application/json",
    Authorization:
      "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmMTQ3ZmUxM2Y4MjhiZDFlNjkyZTA3ZWY2YWZlYTg1ZCIsInN1YiI6IjY1ZDU3YmYyZWQyYWMyMDE2MzM0ODI3OCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.5sfQWHvtlgYclzy94MSofLqdfIgknzXmGN4DbVKJtvE",
  },
};

export const fetchURLs = [
  "https://api.themoviedb.org/3/movie/now_playing?page=1",
  "https://api.themoviedb.org/3/movie/top_rated?page=1",
  "https://api.themoviedb.org/3/movie/upcoming?page=1",
  "https://api.themoviedb.org/3/movie/popular?page=1",
];

export const movieListTitle = [
  "Now Playing",
  "Popular",
  "Top Rated",
  "Upcoming",
];

export const IMAGE_BASE_URL = "https://image.tmdb.org/t/p/";

export const bannerData = [
  {
    adult: false,
    backdrop_path: "/lP0G6f00CjOKdRECyGrT0kaMSrL.jpg",
    genre_ids: [18],
    id: 383634,
    original_language: "ja",
    original_title: "肉体の門",
    overview:
      "Prostitutes in burnt out Tokyo ghetto of post-WWII Japan peddle their flesh and save one-third of their money for a proposed dancehall to be named Paradise. The hookers live in a bombed-out building, but they accept the precarious situation with typical resolve.",
    popularity: 593.877,
    poster_path: "/raNbLci95MJ3L3dMnG7L7bD37lY.jpg",
    release_date: "1988-04-09",
    title: "Carmen 1945",
    video: false,
    vote_average: 4,
    vote_count: 3,
  },
  {
    adult: false,
    backdrop_path: "/uv2twFGMk2qBdyJBJAVcrpRtSa9.jpg",
    genre_ids: [10752, 28, 18],
    id: 929590,
    original_language: "en",
    original_title: "Civil War",
    overview:
      "In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.",
    popularity: 536.288,
    poster_path: "/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg",
    release_date: "2024-04-10",
    title: "Civil War",
    video: false,
    vote_average: 7.521,
    vote_count: 341,
  },
  {
    adult: false,
    backdrop_path: "/e3gVl1gnxEFKLTF6pn6KRqUPi9K.jpg",
    genre_ids: [10749, 18],
    id: 1127166,
    original_language: "it",
    original_title: "Fabbricante di lacrime",
    overview:
      "Adopted together after a tough childhood in an orphanage, Nica and Rigel realize that unexpected but irresistible feelings pull them together.",
    popularity: 400.067,
    poster_path: "/uoBHsxSgfc3PQsSn98RfnbePHOy.jpg",
    release_date: "2024-04-03",
    title: "The Tearsmith",
    video: false,
    vote_average: 6.578,
    vote_count: 423,
  },
  {
    adult: false,
    backdrop_path: "/keVfqCMKmJ55nHzmqR2Q5K7LwJt.jpg",
    genre_ids: [28, 53, 10752],
    id: 784651,
    original_language: "hi",
    original_title: "फाइटर",
    overview:
      "Top IAF aviators come together in the face of imminent danger, to form Air Dragons. Fighter unfolds their camaraderie, brotherhood and battles, internal and external.",
    popularity: 684.849,
    poster_path: "/zDZowwb9GZGEctAu2PCpjiPQAMM.jpg",
    release_date: "2024-01-24",
    title: "Fighter",
    video: false,
    vote_average: 5.487,
    vote_count: 39,
  },
  {
    adult: false,
    backdrop_path: "/2C3CdVzINUm5Cm1lrbT2uiRstwX.jpg",
    genre_ids: [28, 14, 10752],
    id: 856289,
    original_language: "zh",
    original_title: "封神第一部：朝歌风云",
    overview:
      "Based on the most well-known classical fantasy novel of China, Fengshenyanyi, the trilogy is a magnificent eastern high fantasy epic that recreates the prolonged mythical wars between humans, immortals and monsters, which happened more than three thousand years ago.",
    popularity: 347.436,
    poster_path: "/ccJpK0rqzhQeP7Mrs2uKqObFY4L.jpg",
    release_date: "2023-07-20",
    title: "Creation of the Gods I: Kingdom of Storms",
    video: false,
    vote_average: 6.909,
    vote_count: 215,
  },
  {
    adult: false,
    backdrop_path: "/oBIQDKcqNxKckjugtmzpIIOgoc4.jpg",
    genre_ids: [28, 53, 10752],
    id: 969492,
    original_language: "en",
    original_title: "Land of Bad",
    overview:
      "When a Delta Force special ops mission goes terribly wrong, Air Force drone pilot Reaper has 48 hours to remedy what has devolved into a wild rescue operation. With no weapons and no communication other than the drone above, the ground mission suddenly becomes a full-scale battle when the team is discovered by the enemy.",
    popularity: 496.655,
    poster_path: "/h3jYanWMEJq6JJsCopy1h7cT2Hs.jpg",
    release_date: "2024-01-25",
    title: "Land of Bad",
    video: false,
    vote_average: 7.2,
    vote_count: 629,
  },
  {
    adult: false,
    backdrop_path: "/nb3xI8XI3w4pMVZ38VijbsyBqP4.jpg",
    genre_ids: [18, 36],
    id: 872585,
    original_language: "en",
    original_title: "Oppenheimer",
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    popularity: 425.958,
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    release_date: "2023-07-19",
    title: "Oppenheimer",
    video: false,
    vote_average: 8.109,
    vote_count: 7760,
  },
  {
    adult: false,
    backdrop_path: "/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg",
    genre_ids: [878, 12],
    id: 438631,
    original_language: "en",
    original_title: "Dune",
    overview:
      "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
    popularity: 439.551,
    poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    release_date: "2021-09-15",
    title: "Dune",
    video: false,
    vote_average: 7.8,
    vote_count: 11376,
  },
  {
    adult: false,
    backdrop_path: "/wUp0bUXaveR40ikBhDgWwNTijuD.jpg",
    genre_ids: [28, 9648, 53],
    id: 1181548,
    original_language: "en",
    original_title: "Heart of the Hunter",
    overview:
      "A retired assassin is pulled back into action when his friend uncovers a dangerous conspiracy at the heart of the South African government.",
    popularity: 353.973,
    poster_path: "/n726fdyL1dGwt15bY7Nj3XOXc4Q.jpg",
    release_date: "2024-03-28",
    title: "Heart of the Hunter",
    video: false,
    vote_average: 5.885,
    vote_count: 74,
  },
  {
    adult: false,
    backdrop_path: "/deLWkOLZmBNkm8p16igfapQyqeq.jpg",
    genre_ids: [14, 28, 12],
    id: 763215,
    original_language: "en",
    original_title: "Damsel",
    overview:
      "A young woman's marriage to a charming prince turns into a fierce fight for survival when she's offered up as a sacrifice to a fire-breathing dragon.",
    popularity: 359.254,
    poster_path: "/AgHbB9DCE9aE57zkHjSmseszh6e.jpg",
    release_date: "2024-03-07",
    title: "Damsel",
    video: false,
    vote_average: 7.148,
    vote_count: 1650,
  },
  {
    adult: false,
    backdrop_path: "/b4xaqpUZFUkgyJ1VcFEPXmDML34.jpg",
    genre_ids: [27],
    id: 845783,
    original_language: "en",
    original_title: "Baghead",
    overview:
      "Following the death of her estranged father, Iris learns she has inherited a run-down, centuries-old pub. She travels to Berlin to identify her father’s body and meet with The Solicitor to discuss the estate. Little does she know, when the deed is signed she will become inextricably tied to an unspeakable entity that resides in the pub’s basement – Baghead – a shape-shifting creature that can transform into the dead.",
    popularity: 298.096,
    poster_path: "/lbOyeiiRYAE6Nm2e7xiNAAaRwZB.jpg",
    release_date: "2023-12-28",
    title: "Baghead",
    video: false,
    vote_average: 6.729,
    vote_count: 142,
  },
  {
    adult: false,
    backdrop_path: "/ySgY4jBvZ6qchrxKnBg4M8tZp8V.jpg",
    genre_ids: [27, 53, 35],
    id: 1111873,
    original_language: "en",
    original_title: "Abigail",
    overview:
      "After a group of would-be criminals kidnap the 12 year old ballerina daughter of a powerful underworld figure, all they have to do to collect a $50 million ransom is watch the girl overnight. In an isolated mansion, the captors start to dwindle, one by one, and they discover, to their mounting horror, that they’re locked inside with no normal little girl.",
    popularity: 392.166,
    poster_path: "/5Uq8P6MPj9Ppsns5t82AiCiUaWE.jpg",
    release_date: "2024-04-18",
    title: "Abigail",
    video: false,
    vote_average: 6.8,
    vote_count: 38,
  },
  {
    adult: false,
    backdrop_path: "/mIBG74mhGEJnBubhYLkCtvplcNr.jpg",
    genre_ids: [27],
    id: 437342,
    original_language: "en",
    original_title: "The First Omen",
    overview:
      "When a young American woman is sent to Rome to begin a life of service to the church, she encounters a darkness that causes her to question her own faith and uncovers a terrifying conspiracy that hopes to bring about the birth of evil incarnate.",
    popularity: 314.276,
    poster_path: "/phUZyA2TVWuS3Kn6Vdokh8HoIYW.jpg",
    release_date: "2024-04-03",
    title: "The First Omen",
    video: false,
    vote_average: 6.7,
    vote_count: 119,
  },
  {
    adult: false,
    backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
    genre_ids: [28, 80, 53],
    id: 385687,
    original_language: "en",
    original_title: "Fast X",
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    popularity: 362.341,
    poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
    release_date: "2023-05-17",
    title: "Fast X",
    video: false,
    vote_average: 7.129,
    vote_count: 5062,
  },
  {
    adult: false,
    backdrop_path: "/qwK9soQmmJ7kRdjLZVXblw3g7AQ.jpg",
    genre_ids: [28, 12, 53, 80],
    id: 7451,
    original_language: "en",
    original_title: "xXx",
    overview:
      'Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government "recruits" him to go on a mission, he\'s not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.',
    popularity: 327.954,
    poster_path: "/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg",
    release_date: "2002-08-09",
    title: "xXx",
    video: false,
    vote_average: 5.929,
    vote_count: 4014,
  },
  {
    adult: false,
    backdrop_path: "/sRLC052ieEzkQs9dEtPMfFxYkej.jpg",
    genre_ids: [878, 18, 28],
    id: 848326,
    original_language: "en",
    original_title: "Rebel Moon - Part One: A Child of Fire",
    overview:
      "When a peaceful colony on the edge of the galaxy finds itself threatened by the armies of the tyrannical Regent Balisarius, they dispatch Kora, a young woman with a mysterious past, to seek out warriors from neighboring planets to help them take a stand.",
    popularity: 383.877,
    poster_path: "/ui4DrH1cKk2vkHshcUcGt2lKxCm.jpg",
    release_date: "2023-12-15",
    title: "Rebel Moon - Part One: A Child of Fire",
    video: false,
    vote_average: 6.375,
    vote_count: 1720,
  },
  {
    adult: false,
    backdrop_path: "/yyFc8Iclt2jxPmLztbP617xXllT.jpg",
    genre_ids: [35, 10751, 14],
    id: 787699,
    original_language: "en",
    original_title: "Wonka",
    overview:
      "Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.",
    popularity: 361.284,
    poster_path: "/qhb1qOilapbapxWQn9jtRCMwXJF.jpg",
    release_date: "2023-12-06",
    title: "Wonka",
    video: false,
    vote_average: 7.191,
    vote_count: 2865,
  },
  {
    adult: false,
    backdrop_path: "/xThuEoirx0vXismkVbnMQqkMkHK.jpg",
    genre_ids: [28, 53],
    id: 849509,
    original_language: "en",
    original_title: "Jade",
    overview:
      "Jade presents the story of a woman who comes between a powerful businessman and a gang leader in their search for a hard drive that could damage the operations of Interpol. Despite grieving for the brother she accidentally killed, the woman is required to use her unique set of skills to retrieve the drive and protect her brother's unborn child being carried by another woman.",
    popularity: 314.658,
    poster_path: "/pqotEkHRbhUPUuX9Gq4U6aJzK55.jpg",
    release_date: "2024-02-16",
    title: "Jade",
    video: false,
    vote_average: 6,
    vote_count: 20,
  },
  {
    adult: false,
    backdrop_path: "/TGsfNWkASegCfAn6ED1b08a9O6.jpg",
    genre_ids: [27, 9648, 53],
    id: 1125311,
    original_language: "en",
    original_title: "Imaginary",
    overview:
      "When Jessica moves back into her childhood home with her family, her youngest stepdaughter Alice develops an eerie attachment to a stuffed bear named Chauncey she finds in the basement. Alice starts playing games with Chauncey that begin playful and become increasingly sinister. As Alice’s behavior becomes more and more concerning, Jessica intervenes only to realize Chauncey is much more than the stuffed toy bear she believed him to be.",
    popularity: 285.804,
    poster_path: "/9u6HEtZJdZDjPGGJq6YEuhPnoan.jpg",
    release_date: "2024-03-06",
    title: "Imaginary",
    video: false,
    vote_average: 6.287,
    vote_count: 235,
  },
  {
    adult: false,
    backdrop_path: "/kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg",
    genre_ids: [28, 12, 878],
    id: 284053,
    original_language: "en",
    original_title: "Thor: Ragnarok",
    overview:
      "Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok, the destruction of his home-world and the end of Asgardian civilization, at the hands of a powerful new threat, the ruthless Hela.",
    popularity: 355.055,
    poster_path: "/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
    release_date: "2017-10-02",
    title: "Thor: Ragnarok",
    video: false,
    vote_average: 7.594,
    vote_count: 20130,
  },
];
